<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductsRepository extends EntityRepository
{
	public function getAllproducts()
	{
		$params= array(
			'published' => 1,
			'sellprice' => 1000,

			);
		$query = $this->createQueryBuilder('p')
		    ->select('p.name, p.sellprice, cat.name as categoryName')
		    ->leftJoin('p.category', 'cat')
		    ->where('p.published = :published')
		    ->andWhere('p.sellprice >= :sellprice')
		    ->setParameters($params)
		    ->orderBy('p.created', 'DESC')
		    ->getQuery();

		$products = $query->getResult();

		return $products;

	}

	public function createProduct(){

	}
}
